# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
#image: registry.gitlab.com/pages/hugo/hugo_extended:latest

#official reg seems to lag behind by a few days
#image: registry.gitlab.com/thomasdstewart/hugo/hugo_extended:0.84.3

image:
  name: registry.gitlab.com/pages/hugo/hugo_extended:latest
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - main

pages:
  script:
    - apk add go git
    - hugo version
    - hugo mod graph
    - hugo --debug --minify
  artifacts:
    paths:
    - public
  only:
  - main
